// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Student_setPassportNumber8bba5b77d0Test {

    @InjectMocks
    private Student student;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetPassportNumberSuccess() {
        String passportNumber = "123456789";
        student.setPassportNumber(passportNumber);
        assertEquals(passportNumber, student.getPassportNumber());
    }

    @Test
    public void testSetPassportNumberNull() {
        String passportNumber = null;
        assertThrows(NullPointerException.class, () -> student.setPassportNumber(passportNumber));
    }
}