// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.jdbc.core.JdbcTemplate;

import static org.mockito.Mockito.*;

public class StudentJdbcRepository_update40cb1dc622Test {
    
    @InjectMocks
    StudentJdbcRepository studentJdbcRepository;

    @Mock
    JdbcTemplate jdbcTemplate;
    
    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testUpdateSuccess() {
        Student student = new Student();
        student.setId(1);
        student.setName("John");
        student.setPassportNumber("A1234567");

        when(jdbcTemplate.update(anyString(), anyString(), anyString(), anyInt())).thenReturn(1);

        int updatedRows = studentJdbcRepository.update(student);

        Assertions.assertEquals(1, updatedRows);
    }

    @Test
    public void testUpdateFailure() {
        Student student = new Student();
        student.setId(1);
        student.setName("John");
        student.setPassportNumber("A1234567");

        when(jdbcTemplate.update(anyString(), anyString(), anyString(), anyInt())).thenReturn(0);

        int updatedRows = studentJdbcRepository.update(student);

        Assertions.assertEquals(0, updatedRows);
    }
}