// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_getPassportNumberaa3bc55c5bTest {

    @InjectMocks
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetPassportNumber() {
        String expectedPassportNumber = "123456789";
        student.setPassportNumber(expectedPassportNumber);
        String actualPassportNumber = student.getPassportNumber();
        assertEquals(expectedPassportNumber, actualPassportNumber);
    }

    @Test
    public void testGetPassportNumberWhenNoPassportNumberIsSet() {
        String actualPassportNumber = student.getPassportNumber();
        assertEquals(null, actualPassportNumber);
    }
}