// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SpringBoot2JdbcWithH2Application_runac13b209c7Test {

    @Test
    public void testApplicationRun() {
        SpringBoot2JdbcWithH2Application application = new SpringBoot2JdbcWithH2Application();
        assertEquals(true, application.run());
    }
}

// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_Student79727d4203Test {

    @Test
    public void testStudentConstructor() {
        Student student = new Student("John Doe", "123456789");
        assertEquals("John Doe", student.getName());
        assertEquals("123456789", student.getPassportNumber());
    }

    @Test
    public void testStudentConstructorWithEmptyValues() {
        Student student = new Student("", "");
        assertEquals("", student.getName());
        assertEquals("", student.getPassportNumber());
    }

    @Test
    public void testStudentConstructorWithNullValues() {
        Student student = new Student(null, null);
        assertEquals(null, student.getName());
        assertEquals(null, student.getPassportNumber());
    }
}

// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class SpringBoot2JdbcWithH2Application_main1500208c1dTest {

    @Test
    public void testMainMethod() {
        SpringBoot2JdbcWithH2Application.main(new String[]{});
        assertEquals(true, SpringBoot2JdbcWithH2Application.isApplicationStarted());
    }
}