// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class Student_setNamea0b4b9622dTest {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetName() {
        String expectedName = "John Doe";
        student.setName(expectedName);
        Assertions.assertEquals(expectedName, student.getName(), "The name of the student should be set correctly.");
    }

    @Test
    public void testSetName_Null() {
        Assertions.assertThrows(NullPointerException.class, () -> {
            student.setName(null);
        }, "Setting name to null should throw NullPointerException.");
    }

    @Test
    public void testSetName_Empty() {
        String expectedName = "";
        student.setName(expectedName);
        Assertions.assertEquals(expectedName, student.getName(), "Setting name to an empty string should be allowed.");
    }
}