// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setIde5ec36044aTest {

    @InjectMocks
    Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetIdSuccess() {
        Long expectedId = 123L;
        student.setId(expectedId);
        assertEquals(expectedId, student.getId(), "The ID set in the student object does not match the expected ID.");
    }

    @Test
    public void testSetIdNull() {
        Long expectedId = null;
        student.setId(expectedId);
        assertEquals(expectedId, student.getId(), "The ID set in the student object does not match the expected ID (null).");
    }
}