// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class Student_getId68eb246cfdTest {

    @InjectMocks
    private Student student;

    @Mock
    private Long id;

    @Before
    public void setUp() {
        // TODO: Change the value of id as per your requirement
        when(id).thenReturn(1L);
    }

    @Test
    public void testGetIdSuccess() {
        assertEquals(Long.valueOf(1L), student.getId());
    }

    @Test
    public void testGetIdFailure() {
        // TODO: Change the value of id as per your requirement
        when(id).thenReturn(2L);
        assertEquals(Long.valueOf(1L), student.getId());
    }
}