// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;

public class Student_toString6ab14901b5Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = Mockito.mock(Student.class);
    }

    @Test
    public void testToString() {
        Mockito.when(student.getId()).thenReturn(1);
        Mockito.when(student.getName()).thenReturn("John Doe");
        Mockito.when(student.getPassportNumber()).thenReturn("123456");
        Mockito.when(student.toString()).thenCallRealMethod();

        String expected = "Student [id=1, name=John Doe, passportNumber=123456]";
        String actual = student.toString();

        Assertions.assertEquals(expected, actual);
    }

    @Test
    public void testToStringWithNullValues() {
        Mockito.when(student.getId()).thenReturn(null);
        Mockito.when(student.getName()).thenReturn(null);
        Mockito.when(student.getPassportNumber()).thenReturn(null);
        Mockito.when(student.toString()).thenCallRealMethod();

        String expected = "Student [id=null, name=null, passportNumber=null]";
        String actual = student.toString();

        Assertions.assertEquals(expected, actual);
    }
}