// Test generated by RoostGPT for test testJune29 using AI Model gpt

package com.in28minutes.springboot.jdbc.h2.example.student;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.junit.Before;
import org.junit.Test;

public class StudentJdbcRepository_mapRowfa6dd4662aTest {

    private ResultSet rs;
    private StudentJdbcRepository studentJdbcRepository;

    @Before
    public void setUp() {
        rs = mock(ResultSet.class);
        studentJdbcRepository = new StudentJdbcRepository();
    }

    @Test
    public void testMapRow() throws SQLException {
        when(rs.getLong("id")).thenReturn(1L);
        when(rs.getString("name")).thenReturn("John Doe");
        when(rs.getString("passport_number")).thenReturn("P1234567");

        Student student = studentJdbcRepository.mapRow(rs, 1);

        assertEquals(1L, student.getId().longValue());
        assertEquals("John Doe", student.getName());
        assertEquals("P1234567", student.getPassportNumber());
    }

    @Test(expected = SQLException.class)
    public void testMapRowWithException() throws SQLException {
        when(rs.getLong("id")).thenThrow(SQLException.class);

        studentJdbcRepository.mapRow(rs, 1);
    }
}